knpu_oauth2_client:
    clients:
        github:
            type: github
            client_id: '%env(OAUTH_GITHUB_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GITHUB_CLIENT_SECRET)%'
            redirect_route: register_github_check
            redirect_params: {}
            use_state: true
        gitlab:
            type: gitlab
            client_id: '%env(OAUTH_GITLAB_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GITLAB_CLIENT_SECRET)%'
            redirect_route: register_gitlab_check
            redirect_params: {}
            use_state: true
            domain: '%env(APP_GITLAB_API_URL)%'
        bitbucket:
            type: bitbucket
            client_id: '%env(OAUTH_BITBUCKET_CLIENT_ID)%'
            client_secret: '%env(OAUTH_BITBUCKET_CLIENT_SECRET)%'
            redirect_route: register_bitbucket_check
            redirect_params: {}
            use_state: true
        buddy:
            type: generic
            provider_class: Buddy\OAuth2\Client\Provider\Buddy
            client_id: '%env(OAUTH_BUDDY_CLIENT_ID)%'
            client_secret: '%env(OAUTH_BUDDY_CLIENT_SECRET)%'
            redirect_route: register_buddy_check
            redirect_params: {}
            use_state: true
