twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/bootstrap_4_layout.html.twig']
    paths:
        '%kernel.project_dir%/public': public
    globals:
        ga_tracking: '%env(resolve:GA_TRACKING)%'
        ga4_tracking: '%env(resolve:GA4_TRACKING)%'
        config: '@Buddy\Repman\Service\Config'
