controllers:
    resource: ../../src/Controller/
    type: annotation

app_logout:
    path: /logout

proxy_repo_url:
    path: ''
    schemes: ['%url_scheme%']
    host: 'repo{domain_separator}{domain}'
    defaults:
        domain: '%domain%'
        domain_separator: '%domain_separator%'
    requirements:
        domain: "%domain%"
        domain_separator: '%domain_separator%'

organization_repo_url:
    path: ''
    schemes: ['%url_scheme%']
    host: '{organization}{sep1}repo{sep2}{domain}'
    defaults:
        domain: '%domain%'
        sep1: '%organization_separator%'
        sep2: '%domain_separator%'
    requirements:
        domain: '%domain%'
        sep1: '%organization_separator%'
        sep2: '%domain_separator%'

login_github_check:
    path: /auth/github/check
    schemes: ['%url_scheme%']

login_gitlab_check:
    path: /auth/gitlab/check
    schemes: ['%url_scheme%']

login_bitbucket_check:
    path: /auth/bitbucket/check
    schemes: ['%url_scheme%']

login_buddy_check:
    path: /auth/buddy/check
    schemes: ['%url_scheme%']
