php_owner: "{{ system_user }}"
php_group: "{{ system_user }}"

php_listen_owner: 'www-data'
php_listen_group: 'www-data'

php_fastcgi_listen: "/run/php/www.sock"
php_upload_max_filesize: "{{ nginx_client_max_body_size }}"
php_post_max_size: "{{ nginx_client_max_body_size }}"
php_memory_limit: "512M"
php_max_execution_time: 30

php_version: "7.4"

php_packages:
  - php{{ php_version }}-cli
  - php{{ php_version }}-common
  - php{{ php_version }}-curl
  - php{{ php_version }}-fpm
  - php{{ php_version }}-json
  - php{{ php_version }}-opcache
  - php{{ php_version }}-pdo
  - php{{ php_version }}-pgsql
  - php{{ php_version }}-xml
  - php{{ php_version }}-intl
  - php{{ php_version }}-mbstring
  - php{{ php_version }}-zip

php_fpm_max_children: 45
php_fpm_start_servers: 8
php_fpm_min_spare_servers: 4
php_fpm_max_spare_servers: 8
