parameters:
    dists_dir: '%kernel.project_dir%/tests/Resources'
    repo_dir: '%kernel.project_dir%/tests/Resources'
    security_advisories_db_dir: '%kernel.project_dir%/tests/Resources/security-advisories'

services:
    Buddy\Repman\Service\Downloader:
        class: Buddy\Repman\Tests\Doubles\FakeDownloader

    Buddy\Repman\Service\Cache:
        class: Buddy\Repman\Service\Cache\InMemoryCache

    Buddy\Repman\Service\Organization\TokenGenerator:
        class: Buddy\Repman\Tests\Doubles\FakeTokenGenerator

    Buddy\Repman\Service\PackageSynchronizer:
        class: Buddy\Repman\Tests\Doubles\FakePackageSynchronizer

    Buddy\Repman\Service\GitHubApi:
        class: Buddy\Repman\Tests\Doubles\FakeGitHubApi

    Buddy\Repman\Service\GitLabApi:
        class: Buddy\Repman\Tests\Doubles\FakeGitLabApi

    Buddy\Repman\Service\BitbucketApi:
        class: Buddy\Repman\Tests\Doubles\FakeBitbucketApi

    Buddy\Repman\Service\BuddyApi:
        class: Buddy\Repman\Tests\Doubles\FakeBuddyApi

    Buddy\Repman\Tests\Doubles\HttpClientStub:

    Buddy\Repman\Service\PackageScanner:
        class: Buddy\Repman\Tests\Doubles\FakePackageScanner
